# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Quiz' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Quiz
  pod 'SkyFloatingLabelTextField', '~> 3.0'
  pod 'GoogleMaps'
  pod 'SnapKit'
  pod 'Kingfisher', '~> 3.0'
  
  #Firebase
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  
  target 'QuizTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
